site_name: Datashare Python
# TODO: set the domain
site_url: https://mydomain.org/
repo_name: ICIJ/datashare-python
repo_url: https://github.com/ICIJ/datashare-python
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/datashare-logo-color-square.svg
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: [ "docs/src" ]
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - termynal
nav:
  - Home: index.md
  - Learn:
    - learn/index.md
    - Concepts and definitions:
      - Basic: learn/concepts-basic.md
      - Advanced: learn/concepts-advanced.md
    - From functions to tasks:
      - Creating async tasks: learn/tasks.md
      - Building an app: learn/app.md
      - Running a worker pool with the icij-worker CLI: learn/run-worker.md
    - Create tasks for Datashare: learn/datashare-app.md
  - Get started: get-started/index.md
  - Guides:
    - guides/index.md
    - Configuration:
      - Config files and env vars: guides/config/config-files-and-env-vars.md
      - Worker config: guides/config/worker-config.md
      - App config: guides/config/app-config.md
    - Deploy with Docker: guides/deploy-with-docker.md
    - Dependency injection: guides/dependency-injection.md
    - Datashare index read and writes: guides/datashare-index.md
    - Task workflows: guides/task-workflows.md
    - Task routing: guides/task-routing.md
    - Failure recovery: guides/failure-recovery.md
    - Testing: guides/testing.md
    - Progress updates: guides/progress-updates.md
  - FAQ: faq.md
