name: Publish workflows-worker

on:
  workflow_dispatch:
    inputs:
      worker:
        description: 'Worker app to update'
        required: true
        type: choice
        options:
          - asr-worker
          - translation-worker
      worker_version:
        description: 'New version of the worker app'
        required: true
        type: string

env:
  WORKER: ${{ inputs.worker }}
  WORKER_VERSION: ${{ inputs.worker_version }}
  PYTHON_VERSION: 3.12
  ASTRAL_VERSION: 0.11.6

jobs:
  bump-workflows-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # We checkout main to avoid creating a tag from a detached head
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.ASTRAL_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          working-directory: workers/workflows-worker
      - name: Bump workflows worker
        id: bump-workflows-worker
        run: |
          cd workers/workflows-worker
          worker=datashare-"$WORKER"
          workflows_worker_version_info=$(uv run --frozen main.py "$worker" "$WORKER_VERSION")
          workflows_worker_version=$(echo $workflows_worker_version_info | jq -r .next)
          echo workflows_worker_version="$workflows_worker_version" >> "$GITHUB_ENV"
          ./bump_workflow.sh "$worker" "$WORKER_VERSION"
      - name: Create a workflows worker tags
        run: |
          tag=workflows-version-"$workflows_worker_version"
          git pull --rebase
          git "$tag" 
          git push && git push --tags
          gh release create "$tag" --generate-notes

  publish-workflows-worker:
    runs-on: ubuntu-latest
    needs: bump-workflows-worker
    steps:
      - uses: actions/checkout@v6
        with:
          # We checkout main to avoid creating a tag from a detached head
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: icij/datashare-workflows-worker
          tags: |
            type=match,pattern=workflows-worker-(.*),group=1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # You'll need to set these secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          target: io-worker
          context: "{{defaultContext}}:workers/workflows-worker"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
