name: Publish asr-worker

on:
  workflow_dispatch:
  push:
    tags:
      - 'asr-worker-*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12
      ASTRAL_VERSION: 0.11.6
    steps:
      - uses: actions/checkout@v6
      - name: Create GH release
        run: gh release create "$tag" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.ASTRAL_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          working-directory: workers/asr-worker
      - name: Upload available models
        run: |
          cd workers/asr-worker
          uv run --extra cli asr-worker models list-available > available-models.json
          gh release upload "$tag" available-models.json
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish-io-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: icij/asr-transcription-io-worker
          tags: |
            type=match,pattern=asr-worker-(.*),group=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # You'll need to set these secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          target: io-worker
          context: "{{defaultContext}}:workers/asr-worker"
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-preprocessing-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: icij/asr-transcription-preprocessing-worker
          tags: |
            type=match,pattern=asr-worker-(.*),group=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # You'll need to set these secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          target: preprocessing-worker
          context: "{{defaultContext}}:workers/asr-worker"
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-inference-gpu-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: icij/asr-transcription-inference-gpu-worker
          tags: |
            type=match,pattern=asr-worker-(.*),group=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # You'll need to set these secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          target: inference-gpu-worker
          context: "{{defaultContext}}:workers/asr-worker"
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
