name: Test caul

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'caul/**.py'
      - 'caul/pyproject.toml'
      - 'caul/uv.lock'
      - 'caul-core/**.py'
      - 'caul-core/pyproject.toml'
      - 'caul-core/uv.lock'
  pull_request:
    paths:
      - 'caul/**.py'
      - 'caul/pyproject.toml'
      - 'caul/uv.lock'
      - 'caul-core/**.py'
      - 'caul-core/pyproject.toml'
      - 'caul-core/uv.lock'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "--version" # skips test by displaying the version
          version: "0.16.1"
      - name: Check formatting
        run: ruff format --config qa/ruff.toml --check caul caul-core
      - name: Lint test
        run: ruff check --config qa/ruff.toml caul caul-core

  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12
      ASTRAL_VERSION: 0.11.6
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.ASTRAL_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          working-directory: caul
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Run tests
        run: |
          cd caul
          uv run --frozen --dev --extra preprocessing --extra nemo --extra pyannote --extra fireredasr2 --extra faster-whisper --extra cpu python -m pytest -vvv --cache-clear --show-capture=all -r A tests -m "not no_ci"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
