name: Test doc

on:
  push:
    branches: [ 'main' ]
  pull_request:
    paths:
      - 'docs/**'

# TODO: leverage some caching here
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version" # skips test by displaying the version
      - name: Check formatting
        run: ruff format --config qa/ruff.toml --check docs
      - name: Lint test
        run: ruff check --config qa/ruff.toml docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
